---
files: "pointpats\/|docs\/"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.4"
    hooks:
      - id: ruff-format
      - id: ruff-check

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
