name: pointpats
channels:
  - conda-forge
dependencies:
  - python
  - geopandas
  - libpysal
  - matplotlib
  # - numba  -- leave off for now; numba-izde code seems broken
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - shapely
